#!/bin/sh
set -e

if [ -z "${URL}" ] ; then
    echo 1>&2 "Environment variable URL is missing."
    exit 1
fi

export PORT_CALDAV="${PORT_CALDAV:-1080}"
export PORT_IMAP="${PORT_IMAP:-1143}"
export PORT_LDAP="${PORT_LDAP:-1389}"
export PORT_POP="${PORT_POP:-1110}"
export PORT_SMTP="${PORT_SMTP:-1025}"
export SMTP_SAVE_IN_SENT="${SMTP_SAVE_IN_SENT:-false}"

envsubst '${URL}:${PORT_CALDAV}:${PORT_IMAP}:${PORT_LDAP}:${PORT_POP}:${PORT_SMTP}:${SMTP_SAVE_IN_SENT}' < /etc/davmail/davmail.properties.template > /etc/davmail/davmail.properties
